name: "Auto-label Community Issues"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read 
  issues: write
  pull-requests: write
  
jobs:
  community-labeling:
    uses: tenstorrent/tt-github-actions/.github/workflows/issues-community-autotag.yml@main
    secrets:
      AUTOLABEL_COMMUNITY_ISSUES: ${{ secrets.AUTOLABEL_COMMUNITY_ISSUES }}
